spring.application.name=InsuranceCompany
spring.datasource.url=jdbc:postgresql://localhost:5433/insurance_company
spring.datasource.username=postgres
spring.datasource.password=133221
spring.jpa.hibernate.ddl-auto=update    
spring.jpa.show-sql=true